"""
Config parser for the required plain-text format:

Line 1: algoritmo_escalonamento;quantum[;alpha]
Line 2+: id;cor;ingresso;duracao;prioridade;lista_eventos

- "lista_eventos" is parsed into structured TaskEvent objects (for future use in Project B):
    * IO:xx-yy   -> operação de E/S iniciada em xx (rel. ao início da tarefa) com duração yy.
    * MLnn:tt    -> solicitação (lock) do mutex nn no instante tt (rel. ao início da tarefa).
    * MUnn:tt    -> liberação (unlock) do mutex nn no instante tt.
- Defaults: quantum=2, prioridade=1. Colors may be autogenerated if empty.
- Validations: ingresso >= 0, duracao > 0.

Esta versão foi estendida para suportar os formatos usados nos arquivos de teste
do professor, incluindo:

- Cabeçalhos do tipo PRIOPEnv;Q;alpha (mapeados internamente para algoritmo PRIOP
  com parâmetro de envelhecimento alpha).
- Cores sem "#", como "FF0000" (normalizadas para "#FF0000").
- Eventos espalhados em múltiplas colunas separadas por ";" (em vez de um único
  campo separado por vírgulas).
- Variações de sintaxe em IO como "IO-6-1", que são normalizadas para "IO:6-1".
"""
from dataclasses import dataclass, field
from typing import List, Optional

from ..core import TaskEvent


@dataclass
class TaskConfig:
    pid: str
    color: str
    arrival: int
    duration: int
    priority: int = 1
    events: List[TaskEvent] = field(default_factory=list)


@dataclass
class SimulationConfig:
    algorithm: str
    quantum: int
    tasks: List[TaskConfig]
    # Optional aging parameter (alpha), only meaningful for some algorithms (e.g., priority+aging).
    alpha: Optional[int] = None


def _parse_int(name: str, value: str, lineno: Optional[int] = None) -> int:
    try:
        return int(value)
    except Exception:
        if lineno is not None:
            raise ValueError(f"Line {lineno}: invalid integer for {name!r}: {value!r}")
        raise ValueError(f"Invalid integer for {name!r}: {value!r}")


def _parse_events(raw: str, lineno: int) -> List[TaskEvent]:
    """
    Parse the "lista_eventos" (já normalizada) em uma lista de TaskEvent.

    Formato esperado (após normalização):
      - IO:xx-yy     -> I/O iniciada em xx (rel. ao início da tarefa), duração yy
      - MLnn:tt      -> mutex lock nn no instante tt
      - MUnn:tt      -> mutex unlock nn no instante tt

    A normalização prévia lida com variações como "IO-6-1" -> "IO:6-1".
    """
    events: List[TaskEvent] = []
    if not raw:
        return events

    for token in raw.split(","):
        token = token.strip()
        if not token:
            continue

        # Normaliza variações "IO-6-1" para "IO:6-1"
        if token.upper().startswith("IO-"):
            token = "IO:" + token[3:]

        # I/O event
        if token.upper().startswith("IO:"):
            body = token[3:]
            try:
                at_s, dur_s = body.split("-")
            except ValueError:
                raise ValueError(
                    f"Line {lineno}: invalid IO event format {token!r}, expected 'IO:xx-yy'"
                )
            at = _parse_int("io_at", at_s, lineno)
            dur = _parse_int("io_dur", dur_s, lineno)
            if at < 0:
                raise ValueError(f"Line {lineno}: IO start time must be >= 0")
            if dur <= 0:
                raise ValueError(f"Line {lineno}: IO duration must be > 0")
            events.append(TaskEvent(kind="IO", at=at, duration=dur, resource_id=None))
            continue

        # Mutex lock / unlock: MLnn:tt, MUnn:tt
        prefix = token[:2].upper()
        if prefix in ("ML", "MU") and ":" in token:
            head, at_s = token.split(":", 1)
            kind = "ML" if prefix == "ML" else "MU"
            mid_s = head[2:]
            if not mid_s:
                raise ValueError(
                    f"Line {lineno}: mutex id missing in event {token!r}, expected e.g. 'ML01:10'"
                )
            mid = _parse_int("mutex_id", mid_s, lineno)
            at = _parse_int("mutex_at", at_s, lineno)
            if at < 0:
                raise ValueError(f"Line {lineno}: mutex event time must be >= 0")
            events.append(TaskEvent(kind=kind, at=at, duration=None, resource_id=mid))
            continue

        raise ValueError(
            f"Line {lineno}: unknown event token {token!r}. "
            "Expected IO:xx-yy, MLnn:tt or MUnn:tt."
        )

    return events


def parse_config_text(text: str) -> SimulationConfig:
    """
    Faz o parsing de um texto de configuração completo.

    Suporta cabeçalhos do tipo:
      - ALG;quantum
      - ALG;quantum;alpha

    Onde ALG pode ser, por exemplo:
      - FIFO
      - SRTF
      - PRIOP
      - PRIOPEnv  (mapeado internamente para PRIOP com alpha != None)

    Linhas de tarefa:
      pid;cor;ingresso;duracao;prioridade;evento1;evento2;...

    Os eventos adicionais podem vir separados por ';' ou ',', e são
    normalizados antes de chamar _parse_events.
    """
    # remove linhas vazias e comentários
    lines = [ln.strip() for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("#")]
    if not lines:
        raise ValueError("Empty configuration")

    # ------------------------------------------------------------------
    # 1) Cabeçalho: algoritmo;quantum[;alpha]
    # ------------------------------------------------------------------
    header_parts = [p.strip() for p in lines[0].split(";")]
    if len(header_parts) < 2:
        raise ValueError("First line must contain at least algoritmo_escalonamento;quantum.")

    raw_algorithm = header_parts[0].upper()
    quantum_str = header_parts[1]

    quantum = _parse_int("quantum", quantum_str) if quantum_str else 2
    if quantum <= 0:
        raise ValueError("quantum must be > 0")

    alpha: Optional[int] = None
    if len(header_parts) >= 3 and header_parts[2]:
        alpha = _parse_int("alpha", header_parts[2])

    # Mapeia PRIOPEnv -> PRIOP com alpha configurado
    if raw_algorithm == "PRIOPENV":
        algorithm = "PRIOP"
        # se alpha não vier na linha, o chamador pode definir um default
    else:
        algorithm = raw_algorithm

    # ------------------------------------------------------------------
    # 2) Linhas de tarefa
    # ------------------------------------------------------------------
    tasks: List[TaskConfig] = []
    for i, ln in enumerate(lines[1:], start=2):
        cols = [c.strip() for c in ln.split(";")]

        if len(cols) < 5:
            raise ValueError(
                f"Line {i}: each task must have at least pid;color;ingresso;duracao;prioridade"
            )

        pid = cols[0]
        color = cols[1]
        ingresso = cols[2]
        duracao = cols[3]
        prioridade = cols[4]

        if not pid:
            raise ValueError(f"Line {i}: pid must not be empty")

        # normalização de cor:
        if not color:
            # gera cor determinística a partir do pid
            h = abs(hash(pid)) % 0xFFFFFF
            color = f"#{h:06x}"
        else:
            # adiciona '#' se vier sem, como nos arquivos de teste do professor
            if not color.startswith("#"):
                color = "#" + color

        arrival = _parse_int("ingresso", ingresso, i)
        duration = _parse_int("duracao", duracao, i)
        if arrival < 0:
            raise ValueError(f"Line {i}: ingresso must be >= 0")
        if duration <= 0:
            raise ValueError(f"Line {i}: duracao must be > 0")

        priority = _parse_int("prioridade", prioridade, i) if prioridade else 1

        # Coleta de todos os campos de evento (da 6ª coluna em diante).
        raw_event_fields = cols[5:] if len(cols) > 5 else []
        event_tokens: List[str] = []
        for field in raw_event_fields:
            if not field:
                continue
            # aceita tanto ',' quanto ';' como separadores internos
            for tok in field.replace(",", ";").split(";"):
                tok = tok.strip()
                if tok:
                    event_tokens.append(tok)

        # Monta uma string única separada por vírgulas para reaproveitar _parse_events
        if event_tokens:
            joined = ",".join(event_tokens)
            events = _parse_events(joined, i)
        else:
            events = []

        tasks.append(
            TaskConfig(
                pid=pid,
                color=color,
                arrival=arrival,
                duration=duration,
                priority=priority,
                events=events,
            )
        )

    return SimulationConfig(algorithm=algorithm, quantum=quantum, tasks=tasks, alpha=alpha)
